### ISSUE TITLE
未定义的引用

### ISSUE THREAD

**Issue by ThreeBucks** [zg9uagfv/VideoSynopsis#1]
你好，我出现了这种错误：
`
CMakeFiles/video_synopsis.dir/util/classification.cpp.o：在函数‘Classifier::Classifier(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
/home/htt/synopsis/VideoSynopsis-master/src/util/classification.cpp:14：对‘caffe::Net<float>::Net(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, caffe::Phase, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, caffe::Net<float> const*)’未定义的引用
CMakeFiles/video_synopsis.dir/detector/ssd_detect.cpp.o：在函数‘SSD_Detector::SSD_Detector(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float)’中：
/home/htt/synopsis/VideoSynopsis-master/src/detector/ssd_detect.cpp:18：对‘caffe::Net<float>::Net(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, caffe::Phase, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, caffe::Net<float> const*)’未定义的引用
`
请问该如何解决？

**Comment by zg9uagfv** [comment]
你需要到 https://github.com/weiliu89/caffe/tree/ssd 下载编译出库文件，替换与caffe相关的头文件。
